forge 'https://forgeapi.puppetlabs.com'

mod 'puppet-letsencrypt', '4.0.0'
mod 'puppet-nginx', '1.0.0'
mod 'puppet-nodejs', '7.0.1'
mod 'puppet-mongodb', '3.0.0'
mod 'puppetlabs-stdlib', '6.1.0'
mod 'puppetlabs-vcsrepo', '3.0.0'
mod 'puppet-python', '3.0.1'
mod 'puppetlabs-ntp', '7.4.0'
